project_name: cfssl-issuer

release:
  github:
    owner: OpenSource-THG
    name: cfssl-issuer

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^dev:"
      - "README"
      - Merge pull request
      - Merge branch

builds:
  - binary: bin/manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "opensourcethg/cfssl-issuer:latest"
      - "opensourcethg/cfssl-issuer:{{ .Tag }}"
      - "opensourcethg/cfssl-issuer:v{{ .Major }}.{{ .Minor }}"
