project_name: cfssl-issuer

release:
  github:
    owner: opensource-thg
    name: cfssl-issuer

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^dev:"
      - "README"
      - Merge pull request
      - Merge branch

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "thg/cfssl-issuer:latest"
      - "thg/cfssl-issuer:{{ .Tag }}"
      - "thg/cfssl-issuer:v{{ .Major }}.{{ .Minor }}"
