# .travis.yml
language: go

go:
  - 1.12.x
  - 1.13.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

# needed for the docker pipe
services:
  - docker

script:
  - make test

branches:
  only: # speed up CI: don't build pull requests twice
    - "master"
    - /^v\d+\.\d+\.\d+$/

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - echo "travis go version='$TRAVIS_GO_VERSION'"

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.13
