# .travis.yml
language: go

go:
  - 1.13.x
  - master

env:
  - GO111MODULE=on

matrix:
  allow_failures:
    - go: master
  fast_finish: true

# needed for the docker pipe
services:
  - docker

before_install:
  - os=$(go env GOOS)
  - arch=$(go env GOARCH)
  - curl -sL https://go.kubebuilder.io/dl/2.1.0/${os}/${arch} | tar -xz -C /tmp/
  - sudo mv /tmp/kubebuilder_2.1.0_${os}_${arch} /usr/local/kubebuilder

script:
  - make controller-gen
  - go mod download
  - make test

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - echo "travis go version='$TRAVIS_GO_VERSION'"

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.13
