# permissions for end users to edit cfsslclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfsslclusterissuer-editor-role
rules:
- apiGroups:
  - certmanager.thg.io
  resources:
  - cfsslclusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.thg.io
  resources:
  - cfsslclusterissuers/status
  verbs:
  - get
