# permissions for end users to view cfsslclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfsslclusterissuer-viewer-role
rules:
- apiGroups:
  - certmanager.thg.io
  resources:
  - cfsslclusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certmanager.thg.io
  resources:
  - cfsslclusterissuers/status
  verbs:
  - get
