# permissions for end users to edit cfsslissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfsslissuer-editor-role
rules:
- apiGroups:
  - certmanager.thg.io
  resources:
  - cfsslissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.thg.io
  resources:
  - cfsslissuers/status
  verbs:
  - get
