# permissions for end users to view cfsslissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfsslissuer-viewer-role
rules:
- apiGroups:
  - certmanager.thg.io
  resources:
  - cfsslissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certmanager.thg.io
  resources:
  - cfsslissuers/status
  verbs:
  - get
