apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cfssl-issuer-leader-election-role
  namespace: cfssl-issuer-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
