apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cfssl-issuer-leader-election-rolebinding
  namespace: cfssl-issuer-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cfssl-issuer-leader-election-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: cfssl-issuer-system
