name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Import environment from file
        run: cat ".github/env" >> $GITHUB_ENV

      - name: Setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG-VERSION }}

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/release-}" >> $GITHUB_ENV

      - name: Generate release artifact
        run: make create-artifacts IMAGE_TAG=${{ env.RELEASE_VERSION }}

      - name: Upload artifact for release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.repository.name}}.yaml
          name: ${{ env.RELEASE_VERSION }}

